---
abstract: 'Mojolicious Plugin'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-FormFieldsFromJSON-Date
requires:
  Mojolicious: '5.67'
  Mojolicious::Plugin::FormFieldsFromJSON: '0.19'
resources:
  bugtracker: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date/issues
  homepage: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date
  repository: http://github.com/reneeb/Mojolicious-Plugin-FormFieldsFromJSON-Date.git
version: '0.01'
